version: 1.2
workflows:
- name: main
  primaryDescriptorPath: /Pathogen-Detection-Nanopore-SNP-based-pathogenetic-Identification.ga
  publish: true
  subclass: Galaxy
  testParameterFiles:
  - /Pathogen-Detection-Nanopore-SNP-based-pathogenetic-Identification-tests.yml
