version: 1.2
workflows:
- name: main
  primaryDescriptorPath: /Pathogen-Detection-Nanopore-Taxonomy-Profiling-and-Visualization-with-Krona-collection.ga
  publish: true
  subclass: Galaxy
  testParameterFiles:
  - /Pathogen-Detection-Nanopore-Taxonomy-Profiling-and-Visualization-with-Krona-collection-tests.yml
