version: 1.2
workflows:
- name: main
  primaryDescriptorPath: /Pathogen-Detection-Nanopore-Pre-Processing.ga
  publish: true
  subclass: Galaxy
  testParameterFiles:
  - /Pathogen-Detection-Nanopore-Pre-Processing-tests.yml
