version: 1.2
workflows:
- name: main
  primaryDescriptorPath: /nanopore-preprocessing/Nanopore_Datasets_Pre_Processing_Latest.ga
  publish: true
  subclass: Galaxy
- name: main
  primaryDescriptorPath: /nanopore-gene-based-pathogen-detection/Nanopore_Datasets_Gene_based_pathogenic_Identification.ga
  publish: true
  subclass: Galaxy
- name: main
  primaryDescriptorPath: /nanopore-taxonomy-profiling/Nanopore-Datasets---Taxonomy-Profiling-and-Visualization-with-krona---Latest.ga
  publish: true
  subclass: Galaxy
  testParameterFiles:
  - /nanopore-taxonomy-profiling/Nanopore-Datasets---Taxonomy-Profiling-and-Visualization-with-krona---Latest-tests.yml
- name: main
  primaryDescriptorPath: /nanopore-snp-based-pathogen-detection/Nanopore-Datasets---SNP-based-pathogenetic-Identification.ga
  publish: true
  subclass: Galaxy
  testParameterFiles:
  - /nanopore-snp-based-pathogen-detection/Nanopore-Datasets---SNP-based-pathogenetic-Identification-tests.yml
- name: main
  primaryDescriptorPath: /nanopore-all-samples-phylogenetic-trees-and-heatmap/Nanopore_Datasets_Pathogen_Tracking_among_all_samples.ga
  publish: true
  subclass: Galaxy
