version: 1.2
workflows:
- name: main
  primaryDescriptorPath: /Pathogen-Detection-Nanopore-Gene-based-pathogenic-Identification-collection.ga
  publish: true
  subclass: Galaxy
  testParameterFiles:
  - /Pathogen-Detection-Nanopore-Gene-based-pathogenic-Identification-collection-tests.yml
