version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Pathogen-Detection-Nanopore-Taxonomy-Profiling-and-Visualization-with-Krona.ga
  testParameterFiles:
  - /Pathogen-Detection-Nanopore-Taxonomy-Profiling-and-Visualization-with-Krona-tests.yml
  authors:
  - name: Engy Nasr
    orcid: 0000-0001-9047-4215
    url: https://orcid.org/0000-0001-9047-4215
  - name: "B\xE9r\xE9nice Batut"
    orcid: 0000-0001-9852-1987
    url: https://orcid.org/0000-0001-9852-1987
